version: '3'
services:
  nats:
    image: "nats:1.3.0"
  mongo:
    image: "mongo:4"
  postgres:
    image: "postgres:11.1"
    environment:
      POSTGRES_DB: "content-data"
      POSTGRES_PASSWORD: "mysecretpassword"
  content-data:
    build:
      context: ../../
      dockerfile: content-data/Dockerfile
    depends_on:
      - nats
      - mongo
      - postgres
    environment:
      NODE_ENV: "development"
      LOG_HOST: "mongodb://mongo:27017/winston"
      LOG_FILE: "./dev.log"
      NATS_URL: "nats://nats:4222"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASS: "mysecretpassword"
  content-admin:
    build: 
      context: ../../
      dockerfile: content-admin/Dockerfile
    depends_on:
      - nats
      - mongo
      - postgres
    environment:
      NODE_ENV: "development"
      LOG_HOST: "mongodb://mongo:27017/winston"
      LOG_FILE: "./dev.log"
      NATS_URL: "nats://nats:4222"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASS: "mysecretpassword"
    ports: 
      - "4000:4000"