version: '3'
services:
  nats:
    image: "nats:1.3.0"
  mongo:
    image: "mongo:4"
  content-data:
    build:
      context: ../../
      dockerfile: content-data/Dockerfile
  content-admin:
    build: 
      context: ../../
      dockerfile: content-admin/Dockerfile