version: '3'
services:
  nats:
    image: "nats:1.3.0"
    ports: 
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  mongo:
    image: "mongo:4"
    ports: 
      - "27017:27017"
  postgres:
    image: "postgres:11.1"